package com.server.message;

public enum MessageType {
    REQUEST_USER_NAME,
    NAME,
    REQUEST_USER_PASSWORD,
    REGISTRATION_OR_LOGIN,
    REGISTRATION,
    LOGIN,
    PASSWORD,
    USER_ADDED,
    TEXT_MESSAGE,
    DISABLE_USER,
    STATE_OF_LOGIN,
    SUCCESSFULLY,
    USERNAME_USED,
    REQUEST_CHAT_HISTORY,

    ENTER_ERROR,
    INVALID_LOG_ERROR
}
